name: Docker Image CI

on: 
  pull_request:
    branches: [ "develop" ]
env:
  REGISTRY: docker.io
  IMAGE_NAME: web-api
  

jobs:

  build:

    runs-on: ubuntu-latest
   
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/web-api:latest ${{ secrets.DOCKER_USERNAME }}/web-api:${{ github.sha }}
