name: Docker Image CI

on: 
  pull_request:
    branches: [ "develop" ]
env:
  REGISTRY: docker.io
  IMAGE_NAME: web-api

jobs:

  build:

    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/web-api:${{ github.sha }}
