name: Docker Image CI

on: 
  pull_request:
    branches: [ "develop" ]
env:
  REGISTRY: docker.io
  IMAGE_NAME: web-api
  DOCKERUSERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERPASS: ${{ secrets.DOCKER_PASSWORD }}
  

jobs:

  build:

    runs-on: ubuntu-latest
   
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERUSERNAME }}
          password: ${{ env.DOCKERPASS }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ../../ .
          push: true
          tags: ${{ env.DOCKERUSERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
