name: Docker Image CI

on:
  pull_request:
    branches: [ "develop" ]
env:
  REGISTRY: docker.io
  IMAGE_NAME: web-api
  DOCKERUSERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERPASS: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ env.DOCKERUSERNAME }}
          password: ${{ env.DOCKERPASS }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}"
          push: true
          tags: ${{ env.DOCKERUSERNAME }}/${{ env.IMAGE_NAME }}:latest,${{ env.DOCKERUSERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
